# action.yml
name: 'Deploy to Aptible'
description: 'Deploy an app from a Dockerfile to Aptible'
inputs:
  username:
    description: 'Aptible username'
    required: True
  password:
    description: 'Aptible password'
    required: True
  environment: 
    description: 'Aptible environment'
    required: True
  app:
    description: 'Aptible app'
    required: True
  command:
    description: 'Command to run'
    required: True
outputs:
   status:
    description: "The Success/Failure of the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
